In [2]:
import psycopg2

In [3]:
conn = psycopg2.connect(
    dbname = 'dbretail',
    user = 'dsstudent', 
    password = 'GoBis0ns47#', 
    host = 'dbretailcampaign.cluster-cpkaamuwqi1l.us-east-2.rds.amazonaws.com', 
    port = '5432' 
)

In [4]:
from sqlalchemy import create_engine
import pandas as pd

In [5]:
engine = create_engine('postgresql+psycopg2://dsstudent:GoBis0ns47#@dbretailcampaign.cluster-cpkaamuwqi1l.us-east-2.rds.amazonaws.com:5432/dbretail')

In [6]:
sql_query = 'SELECT * FROM CampaignsHouseholds WHERE HouseholdId BETWEEN 601 AND 800;'
df = pd.read_sql(sql_query, engine)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   campaignid   614 non-null    int64
 1   householdid  614 non-null    int64
dtypes: int64(2)
memory usage: 9.7 KB

In [7]:
df.describe(include = "all")

       campaignid  householdid
count  614.000000   614.000000
mean    15.892508   698.224756
std      7.095584    54.088788
min      1.000000   601.000000
25%     10.000000   653.000000
50%     14.000000   699.000000
75%     20.000000   742.000000
max     30.000000   800.000000

In [13]:
cam_ids = df['campaignid'].values.tolist()

new_cam_ids = list(set(cam_ids))

print(new_cam_ids)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [14]:
engine = create_engine('postgresql+psycopg2://dsstudent:GoBis0ns47#@dbretailcampaign.cluster-cpkaamuwqi1l.us-east-2.rds.amazonaws.com:5432/dbretail')

In [15]:
sql_query1 = 'SELECT * FROM Campaigns WHERE CampaignId IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30);'
df1 = pd.read_sql(sql_query1, engine)
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   campaignid    29 non-null     int64
 1   campaigntype  29 non-null     object
 2   startdaynum   29 non-null     int64
 3   enddaynum     29 non-null     int64
dtypes: int64(3), object(1)
memory usage: 1.0+ KB

In [16]:
df1.describe(include = "all")

        campaignid campaigntype  startdaynum   enddaynum
count    29.000000           29    29.000000   29.000000
unique         NaN            3          NaN         NaN
top            NaN        TypeB          NaN         NaN
freq           NaN           19          NaN         NaN
mean     15.517241          NaN   461.000000  503.655172
std       8.958718          NaN   135.933019  134.928096
min       1.000000          NaN   224.000000  264.000000
25%       8.000000          NaN   356.000000  404.000000
50%      16.000000          NaN   463.000000  495.000000
75%      23.000000          NaN   587.000000  635.000000
max      30.000000          NaN   659.000000  719.000000

In [17]:
df1

    campaignid campaigntype  startdaynum  enddaynum
0            1        TypeB          346        383
1            2        TypeB          351        383
2            3        TypeC          356        412
3            4        TypeB          372        404
4            5        TypeB          377        411
5            6        TypeC          393        425
6            7        TypeB          398        432
7            8        TypeA          412        460
8            9        TypeB          435        467
9           10        TypeB          463        495
10          11        TypeB          477        523
11          12        TypeB          477        509
12          13        TypeA          504        551
13          14        TypeC          531        596
14          16        TypeB          561        593
15          17        TypeB          575        607
16          18        TypeA          587        642
17          19        TypeB          603        635
18          20        TypeC          615        685
19          21        TypeB          624        656
20          22        TypeB          624        656
21          23        TypeB          646        684
22          24        TypeB          659        719
23          25        TypeB          659        691
24          26        TypeA          224        264
25          27        TypeC          237        300
26          28        TypeB          259        320
27          29        TypeB          281        334
28          30        TypeA          323        369