In [34]:
import psycopg2

In [35]:
conn = psycopg2.connect(
    dbname = 'dbretail',
    user = 'dsstudent', 
    password = 'GoBis0ns47#', 
    host = 'dbretailcampaign.cluster-cpkaamuwqi1l.us-east-2.rds.amazonaws.com', 
    port = '5432' 
)

In [36]:
from sqlalchemy import create_engine
import pandas as pd

In [37]:
engine = create_engine('postgresql+psycopg2://dsstudent:GoBis0ns47#@dbretailcampaign.cluster-cpkaamuwqi1l.us-east-2.rds.amazonaws.com:5432/dbretail')

In [38]:
sql_query = 'SELECT * FROM TransactionData WHERE HouseholdId BETWEEN 601 AND 800;'
df = pd.read_sql(sql_query, engine)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216363 entries, 0 to 216362
Data columns (total 13 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   householdid          216363 non-null  int64
 1   cartid               216363 non-null  int64
 2   daynum               216363 non-null  int64
 3   productid            216363 non-null  int64
 4   qty                  216363 non-null  int64
 5   unitshelfprice       0 non-null       object
 6   salesvalue           216363 non-null  float64
 7   storeid              216363 non-null  int64
 8   loyaltydiscount      216363 non-null  float64
 9   transactiontime      216363 non-null  object
 10  weeknum              216363 non-null  int64
 11  coupondiscount       216363 non-null  float64
 12  couponmatchdiscount  216363 non-null  float64
dtypes: float64(4), int64(7), object(2)
memory usage: 21.5+ MB

In [39]:
df.describe(include = "all")

,householdid,cartid,daynum,productid,qty,unitshelfprice,salesvalue,storeid,loyaltydiscount,transactiontime,weeknum,coupondiscount,couponmatchdiscount
count,216363.000000,2.163630e+05,216363.000000,2.163630e+05,216363.000000,0,216363.000000,216363.000000,216363.000000,216363,216363.000000,216363.000000,216363.000000
unique,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,1303,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1636,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,660,NaN,NaN,NaN
mean,699.370230,3.398817e+10,387.984984,2.834370e+06,1.319750,NaN,2.869420,2493.460601,-0.552584,NaN,56.111008,-0.010658,-0.002391
std,54.786416,4.678162e+09,188.383691,3.821436e+06,0.921782,NaN,3.086583,7907.114599,1.263188,NaN,26.911828,0.144594,0.036345
min,601.000000,2.698536e+10,1.000000,2.765800e+04,1.000000,NaN,0.000000,21.000000,-75.000000,NaN,1.000000,-11.990000,-2.700000
25%,653.000000,3.051504e+10,230.000000,9.180860e+05,1.000000,NaN,1.290000,329.000000,-0.690000,NaN,34.000000,0.000000,0.000000
50%,700.000000,3.275998e+10,389.000000,1.027569e+06,1.000000,NaN,2.000000,372.000000,-0.090000,NaN,56.000000,0.000000,0.000000
75%,742.000000,4.007303e+10,549.000000,1.128900e+06,1.000000,NaN,3.390000,424.000000,0.000000,NaN,79.000000,0.000000,0.000000
max,800.000000,4.228992e+10,711.000000,1.827305e+07,72.000000,NaN,261.580000,34280.000000,0.260000,NaN,102.000000,0.000000,0.000000

In [40]:
df_sub = df['productid'].sort_values(ascending=True)

df_sub.describe()

count    2.163630e+05
mean     2.834370e+06
std      3.821436e+06
min      2.765800e+04
25%      9.180860e+05
50%      1.027569e+06
75%      1.128900e+06
max      1.827305e+07
Name: productid, dtype: float64

In [41]:
engine = create_engine('postgresql+psycopg2://dsstudent:GoBis0ns47#@dbretailcampaign.cluster-cpkaamuwqi1l.us-east-2.rds.amazonaws.com:5432/dbretail')

In [42]:
sql_query1 = 'SELECT * FROM Products WHERE ProductId BETWEEN 27658 AND 18273050;'
df1 = pd.read_sql(sql_query1, engine)
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92312 entries, 0 to 92311
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   productid       92312 non-null  int64
 1   manufid         92312 non-null  int64
 2   dept            92312 non-null  object
 3   brand           92312 non-null  object
 4   productdesc     92312 non-null  object
 5   productsubdesc  92312 non-null  object
 6   productstdsize  92312 non-null  object
dtypes: int64(2), object(5)
memory usage: 4.9+ MB

In [43]:
df1.describe(include = "all")

,productid,manufid,dept,brand,productdesc,productsubdesc,productstdsize
count,9.231200e+04,92312.000000,92312,92312,92312,92312,92312
unique,NaN,NaN,44,2,308,2383,4343
top,NaN,NaN,GROCERY,National,GREETING CARDS/WRAP/PARTY SPLY,CARDS EVERYDAY,
freq,NaN,NaN,38992,78524,2785,1005,30594
mean,5.328927e+06,1739.638834,NaN,NaN,NaN,NaN,NaN
std,5.358691e+06,1818.133451,NaN,NaN,NaN,NaN,NaN
min,2.765800e+04,1.000000,NaN,NaN,NaN,NaN,NaN
25%,9.707598e+05,328.000000,NaN,NaN,NaN,NaN,NaN
50%,1.622260e+06,1094.000000,NaN,NaN,NaN,NaN,NaN
75%,9.704778e+06,2266.000000,NaN,NaN,NaN,NaN,NaN
max,1.827302e+07,6477.000000,NaN,NaN,NaN,NaN,NaN

In [44]:
df1.head()

,productid,manufid,dept,brand,productdesc,productsubdesc,productstdsize
0,27658,69,GROCERY,Private,BAKED BREAD/BUNS/ROLLS,MAINSTREAM WHITE BREAD,20 OZ
1,27686,69,GROCERY,Private,ICE CREAM/MILK/SHERBTS,TRADITIONAL,64 OZ
2,27695,69,GROCERY,Private,DINNER MXS:DRY,SKILLET DINNERS,5.8 OZ
3,27697,69,GROCERY,Private,CONDIMENTS/SAUCES,HOT MUSTARD/SPECIALTY MUSTAR,12 OZ
4,27732,69,GROCERY,Private,PAPER HOUSEWARES,PLASTIC/HEAVY PAPER PREM PLATE,24 CT

In [45]:
product_desc = df1['productdesc'].values.tolist()

new_product_desc = list(set(product_desc))

print(new_product_desc)

['BAKING MIXES', 'FD WRAPS/BAGS/TRSH BG', 'DELI MEATS', 'NATURAL VITAMINS', 'LUNCHMEAT', 'FEMININE HYGIENE', 'RESTRICTED DIET', 'BULK FOODS', 'CANDLES/ACCESSORIES', 'JUICE', 'SEAFOOD - SHELF STABLE', 'COLD CEREAL', 'AUTOMOTIVE PRODUCTS', 'TROPICAL FRUIT', 'MEAT SUPPLIES', 'LAUNDRY ADDITIVES', 'FLUID MILK PRODUCTS', 'NEW AGE', 'FRZN BREAKFAST FOODS', 'HAND/BODY/FACIAL PRODUCTS', 'FROZEN PIE/DESSERTS', 'SHAVING CARE PRODUCTS', 'STATIONERY & SCHOOL SUPPLIES', 'BREAKFAST SWEETS', 'DELI SPECIALTIES (RETAIL PK)', 'FLORAL- HARD GOODS', 'DRY BN/VEG/POTATO/RICE', 'FILM AND CAMERA PRODUCTS', 'ROSES', 'LIQUOR', 'COFFEE SHOP SWEET GOODS&RETAIL', 'PWDR/CRYSTL DRNK MX', 'HOUSEHOLD CLEANG NEEDS', 'NEWSPAPER', 'COUPON', 'NO COMMODITY DESCRIPTION', 'FRZN JCE CONC/DRNKS', 'COLD AND FLU', 'HISPANIC', 'BATH TISSUES', 'FOOT CARE PRODUCTS', 'SNACK NUTS', 'NUTS', 'CONTINUITIES', 'ISOTONIC DRINKS', 'CAT FOOD', 'REFRIGERATED', 'ANTACIDS', 'MISC WINE', 'SOFT DRINKS', 'MELONS', 'FROZEN CHICKEN', 'PNT BTR/JELLY/JAMS', 'HALLOWEEN', 'FUEL', 'FRUIT - SHELF STABLE', 'FIRST AID PRODUCTS', 'FRZN FRUITS', 'EASTER LILY', 'HOME HEALTH CARE', 'MARGARINES', 'NDAIRY/TEAS/JUICE/SOD', 'VEGETABLES - ALL OTHERS', 'CONDIMENTS', 'INFANT CARE PRODUCTS', 'DINNER SAUSAGE', 'FRZN MEAT/MEAT DINNERS', 'BREAD', 'SMOKED MEATS', 'MISC. DAIRY', 'SANDWICHES', 'COCOA MIXES', 'EYE AND EAR CARE PRODUCTS', 'FROZEN MEAT', 'SOUP', 'SEWING', 'POPCORN', 'VITAMINS', 'VALUE ADDED FRUIT', 'MAKEUP AND TREATMENT', 'FRZN POTATOES', 'LAXATIVES', 'ELECTRICAL SUPPPLIES', 'SUSHI', 'QUICK SERVICE', 'INSECTICIDES', 'HOME FREEZING & CANNING SUPPLY', 'GARDEN CENTER', 'PASTA SAUCE', 'CAKES', 'FROZEN BREAD/DOUGH', 'LAUNDRY DETERGENTS', 'BAKING NEEDS', 'DIETARY AID PRODUCTS', 'EASTER', 'VALUE ADDED VEGETABLES', 'MILK BY-PRODUCTS', 'FAMILY PLANNING', 'CHARCOAL AND LIGHTER FLUID', 'LAWN AND GARDEN SHOP', 'WAREHOUSE SNACKS', 'BERRIES', 'CIGARS', 'ETHNIC PERSONAL CARE', 'DRY SAUCES/GRAVY', 'FLORAL-FRESH CUT', 'FRZN SEAFOOD', 'DELI SUPPLIES', 'BACON', 'COFFEE', 'STONE FRUIT', 'GRAPES', 'OVERNIGHT PHOTOFINISHING', 'ADULT INCONTINENCE', 'DISHWASH DETERGENTS', 'DIAPERS & DISPOSABLES', 'TICKETS', 'CEREAL/BREAKFAST', 'FRZN ICE', 'PERSONAL CARE APPLIANCES', 'FLORAL-FOLIAGE PLANTS', 'SPRING/SUMMER SEASONAL', 'CRACKERS/MISC BKD FD', 'GIFT & FRUIT BASKETS', 'BAKING', 'HOME FURNISHINGS', 'BROOMS AND MOPS', 'RW FRESH PROCESSED MEAT', 'CANDY - PACKAGED', 'DRY TEA/COFFEE/COCO MIX', 'INFANT FORMULA', 'PEPPERS-ALL', 'BROCCOLI/CAULIFLOWER', 'CHEESES', 'SUNTAN', 'SALAD MIX', 'ORAL HYGIENE PRODUCTS', 'BOUQUET (NON ROSE)', 'FLORAL-ACCESSORIES', 'FLORAL BALLOONS', 'PROCESSED', 'COOKIES/CONES', 'DISPOSIBLE FOILWARE', 'ROLLS', 'AUDIO/VIDEO PRODUCTS', 'DRY MIX DESSERTS', 'FROZEN', 'FLORAL-FLOWERING PLANTS', 'HERBS', 'HOSIERY/SOCKS', 'PROD SUPPLIES', 'APPLES', 'YOGURT', 'GLASSWARE & DINNERWARE', 'HOT DOGS', 'PORTABLE ELECTRIC APPLIANCES', 'ONIONS', 'REFRGRATD JUICES/DRNKS', 'PICKLE/RELISH/PKLD VEG', 'TOYS', 'MISCELLANEOUS HBC', 'FROZEN PACKAGE MEAT', 'HEAT/SERVE', 'COFFEE FILTERS', 'TOMATOES', 'SPICES & EXTRACTS', 'MISCELLANEOUS', 'SYRUPS/TOPPINGS', 'BEEF', 'ORGANICS FRUIT & VEGETABLES', 'NATURAL HBC', 'POTATOES', 'CHICKEN/POULTRY', 'DRIED FRUIT', 'SALAD BAR', 'SPORTS MEMORABLILIA', 'MISCELLANEOUS CROUTONS', 'FACIAL TISS/DNR NAPKIN', 'PEARS', 'SINUS AND ALLERGY', 'SEAFOOD - FROZEN', 'FIREWORKS', 'CHRISTMAS  SEASONAL', 'PHARMACY', 'BEVERAGE', 'IMPORTED WINE', 'HARDWARE SUPPLIES', 'RICE CAKES', 'WATCHES/CALCULATORS/LOBBY', 'BREAKFAST SAUSAGE/SANDWICHES', 'EGGS', 'CHICKEN', 'BOOKSTORE', 'PLASTIC HOUSEWARES', 'GLASSES/VISION AIDS', 'FALL AND WINTER SEASONAL', 'SEASONAL', 'COOKIES', 'COOKWARE & BAKEWARE', 'NON EDIBLE PRODUCTS', 'APPAREL', 'DOG FOODS', 'SNKS/CKYS/CRKR/CNDY', 'GREETING CARDS/WRAP/PARTY SPLY', 'BABY HBC', 'OLIVES', 'TEAS', 'SWEET GOODS & SNACKS', 'BAKERY PARTY TRAYS', 'SALADS/DIPS', 'BAKED BREAD/BUNS/ROLLS', 'PREPARED/PKGD FOODS', 'SEAFOOD-FRESH', 'PKG.SEAFOOD MISC', 'CIGARETTES', 'BLEACH', 'CANNED JUICES', 'MAGAZINE', 'HAIR CARE PRODUCTS', 'J-HOOKS', 'BEANS - CANNED GLASS & MW', 'VEGETABLES SALAD', '(CORP USE ONLY)', 'MUSHROOMS', 'MOLASSES/SYRUP/PANCAKE MIXS', 'BABY FOODS', 'IN-STORE PHOTOFINISHING', 'BOTTLE DEPOSITS', 'BABYFOOD', 'PACKAGED NATURAL SNACKS', 'MISCELLANEOUS(CORP USE ONLY)', 'COUPONS/STORE & MFG', 'IRONING AND CHEMICALS', ' ', 'CAT LITTER', 'LONG DISTANCE CALLING CARDS', 'FLOUR & MEALS', 'BIRD SEED', 'DOMESTIC GOODS', 'TOBACCO OTHER', 'SOAP - LIQUID & BAR', 'SQUASH', 'DEODORANTS', 'LAMB', 'EXOTIC GAME/FOWL', 'DOMESTIC WINE', 'COUPON/MISC ITEMS', 'BAKED SWEET GOODS', 'UNKNOWN', 'PORK', 'CONDIMENTS/SAUCES', 'PET CARE SUPPLIES', 'PREPAID WIRELESS&ACCESSORIES', 'PAPER TOWELS', 'FITNESS&DIET', 'SUGARS/SWEETNERS', 'VEAL', 'PAPER HOUSEWARES', 'VALENTINE', 'BUTTER', 'CARROTS', 'SALD DRSNG/SNDWCH SPRD', 'WATER', 'REFRGRATD DOUGH PRODUCTS', 'TURKEY', 'CANDY - CHECKLANE', 'FROZEN PIZZA', 'CORN', 'SEAFOOD - MISC', 'BATH', 'SHOE CARE', 'TOYS AND GAMES', 'KITCHEN GADGETS', 'BEERS/ALES', 'MEAT - MISC', 'CHEESE', 'BATTERIES', 'PREPARED FOOD', 'DINNER MXS:DRY', 'DOLLAR VALUE PRODUCTS', 'PROPANE', 'FRZN VEGETABLE/VEG DSH', 'AIR CARE', 'COSMETIC ACCESSORIES', 'CANNED MILK', 'HOT CEREAL', 'CONVENIENT BRKFST/WHLSM SNACKS', 'SMOKING CESSATIONS', 'FROZEN - BOXED(GROCERY)', 'PARTY TRAYS', 'CITRUS', 'ICE CREAM/MILK/SHERBTS', 'SERVICE BEVERAGE', 'WATER - CARBONATED/FLVRD DRINK', 'ANALGESICS', 'PIES', 'FRZN NOVELTIES/WTR ICE', 'VEGETABLES - SHELF STABLE', 'BAG SNACKS', 'NON-DAIRY BEVERAGES', 'COFFEE SHOP', 'CHIPS&SNACKS', 'SNACKS', 'DRY NOODLES/PASTA', 'SHORTENING/OIL', 'MEAT - SHELF STABLE', 'HAIR CARE ACCESSORIES', 'FRAGRANCES']

In [50]:
df1_1 = df1[df1['productdesc'] == 'FEMININE HYGIENE']

df1_1

,productid,manufid,dept,brand,productdesc,productsubdesc,productstdsize
383,40650,69,DRUG GM,Private,FEMININE HYGIENE,FEM HYGN DOUCHES,4.5 OZ
418,41580,69,DRUG GM,Private,FEMININE HYGIENE,FEM. HYGN.NAPKINS,16 CT
445,42111,69,DRUG GM,Private,FEMININE HYGIENE,FEM HYGN DOUCHES,4.5 OZ
1568,85340,751,DRUG GM,National,FEMININE HYGIENE,FEM. HYGN. TAMPONS,18 CT
1986,101976,1844,DRUG GM,National,FEMININE HYGIENE,FEM. HYGN. TAMPONS,40 CT
...,...,...,...,...,...,...,...
91070,17214847,2236,DRUG GM,National,FEMININE HYGIENE,FEM. HYGN. TAMPONS,
91071,17214848,2236,DRUG GM,National,FEMININE HYGIENE,FEM. HYGN.NAPKINS,18 CT
91072,17214857,2236,DRUG GM,National,FEMININE HYGIENE,FEM. HYGN. TAMPONS,
91073,17214863,2236,DRUG GM,National,FEMININE HYGIENE,FEM. HYGN.NAPKINS,18 CT
91103,17215080,2236,DRUG GM,National,FEMININE HYGIENE,FEM. HYGN.NAPKINS,18 CT

In [ ]:
df1_1.groupby('productsubdesc')

KeyError: 'productsubdesc'

In [59]:
engine = create_engine('postgresql+psycopg2://dsstudent:GoBis0ns47#@dbretailcampaign.cluster-cpkaamuwqi1l.us-east-2.rds.amazonaws.com:5432/dbretail')

In [60]:
sql_query1 = 'SELECT * FROM CouponCampaigns WHERE ProductId BETWEEN 27658 AND 18273050;'
df1 = pd.read_sql(sql_query1, engine)
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119342 entries, 0 to 119341
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   campaignid  119342 non-null  int64
 1   productid   119342 non-null  int64
 2   couponcode  119342 non-null  int64
dtypes: int64(3)
memory usage: 2.7 MB