In [6]:
import psycopg2

In [7]:
conn = psycopg2.connect(
    dbname = 'dbretail',
    user = 'dsstudent', 
    password = 'GoBis0ns47#', 
    host = 'dbretailcampaign.cluster-cpkaamuwqi1l.us-east-2.rds.amazonaws.com', 
    port = '5432' 
)

In [8]:
from sqlalchemy import create_engine
import pandas as pd

In [9]:
engine = create_engine('postgresql+psycopg2://dsstudent:GoBis0ns47#@dbretailcampaign.cluster-cpkaamuwqi1l.us-east-2.rds.amazonaws.com:5432/dbretail')

In [98]:
sql_query = "SELECT table_name " \
                "FROM information_schema.tables " \
                "WHERE table_schema = 'public' " \
                "AND table_type = 'BASE TABLE';"
df1 = pd.read_sql(sql_query, engine) 
df1

                     table_name
0         householddemographics
1              couponredemption
2               couponcampaigns
3                      products
4               transactiondata
5        transactiondata_subset
6           campaignshouseholds
7                     campaigns
8      advertisementmailadtypes
9             advertisementdata
10  advertisementdisplayadtypes

In [130]:
engine = create_engine('postgresql+psycopg2://dsstudent:GoBis0ns47#@dbretailcampaign.cluster-cpkaamuwqi1l.us-east-2.rds.amazonaws.com:5432/dbretail')

In [137]:
sql_query = "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'campaignshouseholds';"
df = pd.read_sql(sql_query, engine)
df

   column_name
0   campaignid
1  householdid

In [100]:
engine = create_engine('postgresql+psycopg2://dsstudent:GoBis0ns47#@dbretailcampaign.cluster-cpkaamuwqi1l.us-east-2.rds.amazonaws.com:5432/dbretail')

In [14]:
# use product ID (and maybe store ID) to find advertisement for households

sql_query = 'SELECT * FROM advertisementdata WHERE '
df = pd.read_sql(sql_query, engine)
df.info()

ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at end of input
LINE 1: SELECT * FROM advertisementdata WHERE
                                              ^

[SQL: SELECT * FROM advertisementdata WHERE ]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [15]:
engine = create_engine('postgresql+psycopg2://dsstudent:GoBis0ns47#@dbretailcampaign.cluster-cpkaamuwqi1l.us-east-2.rds.amazonaws.com:5432/dbretail')

In [101]:
sql_query = 'SELECT * FROM advertisementdisplayadtypes;'
df = pd.read_sql(sql_query, engine)
df.describe(include = "all")

        displayadid displayadtypedesc
count      9.000000                 9
unique          NaN                 9
top             NaN       Front Aisle
freq            NaN                 1
mean       5.222222               NaN
std        3.073181               NaN
min        1.000000               NaN
25%        3.000000               NaN
50%        5.000000               NaN
75%        7.000000               NaN
max       10.000000               NaN

In [102]:
df.head(10)

   displayadid       displayadtypedesc
0            1             Front Aisle
1            2              Rear Aisle
2            3           Front End Cap
3            4       Mid-Aisle End Cap
4            5            Rear End Cap
5            6      Side-Aisle End Cap
6            7                In-Aisle
7            9  Other Location Display
8           10                In-Shelf

In [18]:
from sqlalchemy import create_engine
import pandas as pd

In [103]:
engine = create_engine('postgresql+psycopg2://dsstudent:GoBis0ns47#@dbretailcampaign.cluster-cpkaamuwqi1l.us-east-2.rds.amazonaws.com:5432/dbretail')

In [104]:
sql_query = 'SELECT * FROM transactiondata_subset WHERE householdid BETWEEN 601 AND 800;'
df = pd.read_sql(sql_query, engine)
df.describe(include = "all")

,householdid,cartid,daynum,productid,qty,unitshelfprice,salesvalue,storeid,loyaltydiscount,transactiontime,weeknum,coupondiscount,couponmatchdiscount
count,73079.000000,7.307900e+04,73079.000000,7.307900e+04,73079.000000,0,73079.000000,73079.000000,73079.000000,73079,73079.000000,73079.000000,73079.000000
unique,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,1132,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1739,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,266,NaN,NaN,NaN
mean,713.712763,3.425930e+10,400.223717,2.881195e+06,1.318819,NaN,2.860925,3650.821057,-0.575948,NaN,57.872316,-0.013851,-0.003207
std,55.941446,4.658042e+09,184.369240,3.881063e+06,0.949279,NaN,3.153743,9644.665013,1.324669,NaN,26.340531,0.157843,0.042215
min,601.000000,2.698536e+10,1.000000,2.765800e+04,1.000000,NaN,0.000000,27.000000,-44.990000,NaN,1.000000,-8.990000,-2.250000
25%,692.000000,3.074359e+10,249.000000,9.175365e+05,1.000000,NaN,1.290000,333.000000,-0.690000,NaN,36.000000,0.000000,0.000000
50%,718.000000,3.295747e+10,403.000000,1.025650e+06,1.000000,NaN,2.000000,360.000000,-0.130000,NaN,58.000000,0.000000,0.000000
75%,762.000000,4.017460e+10,557.000000,1.128665e+06,1.000000,NaN,3.340000,424.000000,0.000000,NaN,80.000000,0.000000,0.000000
max,797.000000,4.228992e+10,711.000000,1.820392e+07,72.000000,NaN,261.580000,34011.000000,0.000000,NaN,102.000000,0.000000,0.000000

In [105]:
df.head(10)

,householdid,cartid,daynum,productid,qty,unitshelfprice,salesvalue,storeid,loyaltydiscount,transactiontime,weeknum,coupondiscount,couponmatchdiscount
0,718,26985360571,1,830503,1,None,2.99,324,-1.00,1115,1,-1.0,0.0
1,718,26985360571,1,839605,1,None,2.50,324,-0.99,1115,1,0.0,0.0
2,718,26985360571,1,840664,1,None,0.55,324,0.00,1115,1,0.0,0.0
3,718,26985360571,1,844685,2,None,1.98,324,-1.60,1115,1,0.0,0.0
4,718,26985360571,1,848015,2,None,1.20,324,-0.18,1115,1,0.0,0.0
5,718,26985360571,1,855325,1,None,1.10,324,-0.69,1115,1,-0.4,-0.4
6,718,26985360571,1,855468,4,None,2.00,324,-1.56,1115,1,0.0,0.0
7,718,26985360571,1,856515,1,None,0.62,324,-0.27,1115,1,0.0,0.0
8,718,26985360571,1,860776,1,None,0.59,324,0.00,1115,1,0.0,0.0
9,718,26985360571,1,862538,1,None,2.50,324,-0.99,1115,1,0.0,0.0

In [106]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73079 entries, 0 to 73078
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   householdid          73079 non-null  int64
 1   cartid               73079 non-null  int64
 2   daynum               73079 non-null  int64
 3   productid            73079 non-null  int64
 4   qty                  73079 non-null  int64
 5   unitshelfprice       0 non-null      object
 6   salesvalue           73079 non-null  float64
 7   storeid              73079 non-null  int64
 8   loyaltydiscount      73079 non-null  float64
 9   transactiontime      73079 non-null  object
 10  weeknum              73079 non-null  int64
 11  coupondiscount       73079 non-null  float64
 12  couponmatchdiscount  73079 non-null  float64
dtypes: float64(4), int64(7), object(2)
memory usage: 7.2+ MB

In [107]:
engine = create_engine('postgresql+psycopg2://dsstudent:GoBis0ns47#@dbretailcampaign.cluster-cpkaamuwqi1l.us-east-2.rds.amazonaws.com:5432/dbretail')

In [108]:
sql_query = 'SELECT * FROM transactiondata_subset WHERE householdid BETWEEN 601 AND 800;'
df = pd.read_sql(sql_query, engine)
df.describe(include = "all")

,householdid,cartid,daynum,productid,qty,unitshelfprice,salesvalue,storeid,loyaltydiscount,transactiontime,weeknum,coupondiscount,couponmatchdiscount
count,73079.000000,7.307900e+04,73079.000000,7.307900e+04,73079.000000,0,73079.000000,73079.000000,73079.000000,73079,73079.000000,73079.000000,73079.000000
unique,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,1132,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1739,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,266,NaN,NaN,NaN
mean,713.712763,3.425930e+10,400.223717,2.881195e+06,1.318819,NaN,2.860925,3650.821057,-0.575948,NaN,57.872316,-0.013851,-0.003207
std,55.941446,4.658042e+09,184.369240,3.881063e+06,0.949279,NaN,3.153743,9644.665013,1.324669,NaN,26.340531,0.157843,0.042215
min,601.000000,2.698536e+10,1.000000,2.765800e+04,1.000000,NaN,0.000000,27.000000,-44.990000,NaN,1.000000,-8.990000,-2.250000
25%,692.000000,3.074359e+10,249.000000,9.175365e+05,1.000000,NaN,1.290000,333.000000,-0.690000,NaN,36.000000,0.000000,0.000000
50%,718.000000,3.295747e+10,403.000000,1.025650e+06,1.000000,NaN,2.000000,360.000000,-0.130000,NaN,58.000000,0.000000,0.000000
75%,762.000000,4.017460e+10,557.000000,1.128665e+06,1.000000,NaN,3.340000,424.000000,0.000000,NaN,80.000000,0.000000,0.000000
max,797.000000,4.228992e+10,711.000000,1.820392e+07,72.000000,NaN,261.580000,34011.000000,0.000000,NaN,102.000000,0.000000,0.000000

In [109]:
from sqlalchemy import create_engine
import pandas as pd

In [110]:
engine = create_engine('postgresql+psycopg2://dsstudent:GoBis0ns47#@dbretailcampaign.cluster-cpkaamuwqi1l.us-east-2.rds.amazonaws.com:5432/dbretail')

In [111]:
sql_query1 = 'SELECT householdid, productid, storeid, weeknum, daynum, transactiontime FROM transactiondata_subset WHERE householdid BETWEEN 601 AND 800;'
df1 = pd.read_sql(sql_query1, engine)
df1.describe(include = "all")

,householdid,productid,storeid,weeknum,daynum,transactiontime
count,73079.000000,7.307900e+04,73079.000000,73079.000000,73079.000000,73079
unique,NaN,NaN,NaN,NaN,NaN,1132
top,NaN,NaN,NaN,NaN,NaN,1739
freq,NaN,NaN,NaN,NaN,NaN,266
mean,713.712763,2.881195e+06,3650.821057,57.872316,400.223717,NaN
std,55.941446,3.881063e+06,9644.665013,26.340531,184.369240,NaN
min,601.000000,2.765800e+04,27.000000,1.000000,1.000000,NaN
25%,692.000000,9.175365e+05,333.000000,36.000000,249.000000,NaN
50%,718.000000,1.025650e+06,360.000000,58.000000,403.000000,NaN
75%,762.000000,1.128665e+06,424.000000,80.000000,557.000000,NaN
max,797.000000,1.820392e+07,34011.000000,102.000000,711.000000,NaN

In [112]:
df1_1 = df1.groupby(['storeid']).count().sort_values(by = 'productid', ascending = False)
df1_1.head(50)

         householdid  productid  weeknum  daynum  transactiontime
storeid
324             6474       6474     6474    6474             6474
343             4765       4765     4765    4765             4765
359             4749       4749     4749    4749             4749
31742           3618       3618     3618    3618             3618
389             3489       3489     3489    3489             3489
448             3431       3431     3431    3431             3431
400             2777       2777     2777    2777             2777
333             2618       2618     2618    2618             2618
323             2409       2409     2409    2409             2409
408             2225       2225     2225    2225             2225
306             2183       2183     2183    2183             2183
339             2046       2046     2046    2046             2046
404             2029       2029     2029    2029             2029
424             1975       1975     1975    1975             1975
31862           1896       1896     1896    1896             1896
369             1873       1873     1873    1873             1873
360             1757       1757     1757    1757             1757
288             1385       1385     1385    1385             1385
356             1299       1299     1299    1299             1299
427             1285       1285     1285    1285             1285
315             1144       1144     1144    1144             1144
335             1139       1139     1139    1139             1139
446             1083       1083     1083    1083             1083
32004           1023       1023     1023    1023             1023
432              889        889      889     889              889
33923            821        821      821     821              821
450              776        776      776     776              776
443              719        719      719     719              719
438              668        668      668     668              668
391              608        608      608     608              608
384              593        593      593     593              593
354              564        564      564     564              564
313              556        556      556     556              556
330              463        463      463     463              463
322              427        427      427     427              427
329              422        422      422     422              422
396              418        418      418     418              418
382              404        404      404     404              404
370              378        378      378     378              378
298              375        375      375     375              375
293              374        374      374     374              374
415              373        373      373     373              373
372              371        371      371     371              371
388              301        301      301     301              301
445              260        260      260     260              260
381              257        257      257     257              257
442              245        245      245     245              245
355              219        219      219     219              219
292              207        207      207     207              207
327              206        206      206     206              206

In [113]:
# storeid = 324
df1_1_1 = df1[df1['storeid'] == 324]
df1_1_1.describe(include = "all")

,householdid,productid,storeid,weeknum,daynum,transactiontime
count,6474.000000,6.474000e+03,6474.0,6474.000000,6474.000000,6474
unique,NaN,NaN,NaN,NaN,NaN,391
top,NaN,NaN,NaN,NaN,NaN,1649
freq,NaN,NaN,NaN,NaN,NaN,152
mean,717.762743,2.729880e+06,324.0,50.087736,345.753939,NaN
std,3.746311,3.758665e+06,0.0,29.367040,205.714131,NaN
min,661.000000,8.193040e+05,324.0,1.000000,1.000000,NaN
25%,718.000000,9.131585e+05,324.0,24.000000,162.000000,NaN
50%,718.000000,1.015974e+06,324.0,51.000000,351.000000,NaN
75%,718.000000,1.124823e+06,324.0,76.000000,528.000000,NaN
max,722.000000,1.810484e+07,324.0,102.000000,707.000000,NaN

In [114]:
df1_1_1.head(20)

    householdid  productid  storeid  weeknum  daynum transactiontime
0           718     830503      324        1       1            1115
1           718     839605      324        1       1            1115
2           718     840664      324        1       1            1115
3           718     844685      324        1       1            1115
4           718     848015      324        1       1            1115
5           718     855325      324        1       1            1115
6           718     855468      324        1       1            1115
7           718     856515      324        1       1            1115
8           718     860776      324        1       1            1115
9           718     862538      324        1       1            1115
10          718     870826      324        1       1            1115
11          718     874317      324        1       1            1115
12          718     874736      324        1       1            1115
13          718     880579      324        1       1            1115
14          718     880895      324        1       1            1115
15          718     885858      324        1       1            1115
16          718     900598      324        1       1            1115
17          718     912553      324        1       1            1115
18          718     913785      324        1       1            1115
19          718     920308      324        1       1            1115

In [115]:
df1_1['transactiontime']

storeid
324      6474
343      4765
359      4749
31742    3618
389      3489
         ...
441         1
2942        1
2883        1
2839        1
3134        1
Name: transactiontime, Length: 116, dtype: int64

In [116]:
df1_1_1.tail(20)

       householdid  productid  storeid  weeknum  daynum transactiontime
72745          718   10355982      324       77     536            1706
72746          718   15778432      324       77     536            2350
72747          718   15778497      324       77     536            2350
72748          718   15449615      324       77     537            0056
72947          718     830245      324       84     586            1538
72948          718     883404      324       84     586            1538
72949          718     934676      324       84     586            1538
72950          718     963971      324       84     586            1538
72951          718     965331      324       84     586            1538
72952          718     970747      324       84     586            1538
72953          718    1019744      324       84     586            1538
72954          718    1045109      324       84     586            1538
72955          718    1054483      324       84     586            1538
72956          718    1066895      324       84     586            1538
72957          718    1092026      324       84     586            1538
72958          718    1136257      324       84     586            1538
72959          718    7149521      324       84     586            1538
72960          718    9396770      324       84     586            1538
72961          718    9445919      324       84     586            1538
72962          718   12263759      324       84     586            1538

In [117]:
df1_1_1['transactiontime'].dtypes

dtype('O')

In [118]:
df1_1_1['transactiontime'].head(20)

0     1115
1     1115
2     1115
3     1115
4     1115
5     1115
6     1115
7     1115
8     1115
9     1115
10    1115
11    1115
12    1115
13    1115
14    1115
15    1115
16    1115
17    1115
18    1115
19    1115
Name: transactiontime, dtype: object

In [119]:
def convert_transac_time(time):
    time = str(time).strip()
    if len(time) < 4:
        time = time.zfill(4)
    hour = int(time[:2])
    min = int(time[2:4])
    return f'{hour:02d}:{min:02d}:00'

df1_1_1.loc[:,'transactiontime'] = df1_1_1['transactiontime'].apply(convert_transac_time)
df1_1_1.loc[:,'transactiontime'] = pd.to_datetime(df1_1_1['transactiontime'], format = "%H:%M:%S")

In [120]:
df1_1_1

       householdid  productid  storeid  weeknum  daynum      transactiontime
0              718     830503      324        1       1  1900-01-01 11:15:00
1              718     839605      324        1       1  1900-01-01 11:15:00
2              718     840664      324        1       1  1900-01-01 11:15:00
3              718     844685      324        1       1  1900-01-01 11:15:00
4              718     848015      324        1       1  1900-01-01 11:15:00
...            ...        ...      ...      ...     ...                  ...
72958          718    1136257      324       84     586  1900-01-01 15:38:00
72959          718    7149521      324       84     586  1900-01-01 15:38:00
72960          718    9396770      324       84     586  1900-01-01 15:38:00
72961          718    9445919      324       84     586  1900-01-01 15:38:00
72962          718   12263759      324       84     586  1900-01-01 15:38:00

[6474 rows x 6 columns]

In [121]:
df1_1.loc[:,'transactiontime'] = df1_1['transactiontime'].apply(convert_transac_time)
df1_1.loc[:, 'transactiontime'] = pd.to_datetime(df1_1['transactiontime'], format = '%H:%M:%S')

C:\Users\ejarr\AppData\Local\Temp\ipykernel_11224\3907699138.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['64:74:00' '47:65:00' '47:49:00' '36:18:00' '34:89:00' '34:31:00'
 '27:77:00' '26:18:00' '24:09:00' '22:25:00' '21:83:00' '20:46:00'
 '20:29:00' '19:75:00' '18:96:00' '18:73:00' '17:57:00' '13:85:00'
 '12:99:00' '12:85:00' '11:44:00' '11:39:00' '10:83:00' '10:23:00'
 '08:89:00' '08:21:00' '07:76:00' '07:19:00' '06:68:00' '06:08:00'
 '05:93:00' '05:64:00' '05:56:00' '04:63:00' '04:27:00' '04:22:00'
 '04:18:00' '04:04:00' '03:78:00' '03:75:00' '03:74:00' '03:73:00'
 '03:71:00' '03:01:00' '02:60:00' '02:57:00' '02:45:00' '02:19:00'
 '02:07:00' '02:06:00' '01:75:00' '01:60:00' '01:44:00' '01:34:00'
 '01:22:00' '01:14:00' '01:09:00' '01:07:00' '01:03:00' '00:99:00'
 '00:96:00' '00:78:00' '00:63:00' '00:63:00' '00:58:00' '00:55:00'
 '00:49:00' '00:48:00' '00:48:00' '00:48:00' '00:47:00' '00:44:00'
 '00:41:00' '00:41:00' '00:37:00' '00:32:00' '00:31:00' '00:29:00'
 '00:26:00' '00:23:00' '00:22:00' '00:21:00' '00:20:00' '00:16:00'
 '00:15:00' '00:14:00' '00:13:00' '00:13:00' '00:12:00' '00:12:00'
 '00:11:00' '00:11:00' '00:11:00' '00:09:00' '00:09:00' '00:08:00'
 '00:08:00' '00:08:00' '00:07:00' '00:07:00' '00:06:00' '00:06:00'
 '00:05:00' '00:04:00' '00:04:00' '00:03:00' '00:02:00' '00:02:00'
 '00:02:00' '00:02:00' '00:01:00' '00:01:00' '00:01:00' '00:01:00'
 '00:01:00' '00:01:00']' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df1_1.loc[:,'transactiontime'] = df1_1['transactiontime'].apply(convert_transac_time)

ValueError: time data "64:74:00" doesn't match format "%H:%M:%S", at position 0. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [122]:
df1_1

         householdid  productid  weeknum  daynum transactiontime
storeid
324             6474       6474     6474    6474        64:74:00
343             4765       4765     4765    4765        47:65:00
359             4749       4749     4749    4749        47:49:00
31742           3618       3618     3618    3618        36:18:00
389             3489       3489     3489    3489        34:89:00
...              ...        ...      ...     ...             ...
441                1          1        1       1        00:01:00
2942               1          1        1       1        00:01:00
2883               1          1        1       1        00:01:00
2839               1          1        1       1        00:01:00
3134               1          1        1       1        00:01:00

[116 rows x 5 columns]